model:
  name: "base_model"
  architecture: "transformer"
  hidden_size: 768
  num_layers: 12
  num_heads: 12
  dropout: 0.1

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  patience: 10
  validation_split: 0.2

data:
  train_path: "data/processed/train.csv"
  val_path: "data/processed/val.csv"
  test_path: "data/processed/test.csv"
  max_length: 512

inference:
  batch_size: 64
  device: "cuda"
  model_path: "data/models/best_model.pth"

logging:
  level: "INFO"
  log_file: "logs/training.log"
  use_wandb: true
  project_name: "ai-system"